// Copyright 2026 The typesafe-sdk-go Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package typesafe

// Code generated by the W6.5 design spike's _gen (D2); the public API is
// declared in internal/engine and re-exported here.

import (
	"context"
	"crypto/tls"
	"crypto/x509"
	"log/slog"
	"net/http"
	"net/http/httptrace"
	"net/url"
	"reflect"
	"time"

	"github.com/zchee/typesafe-sdk-go/internal/engine"
)

// APIError reports an unsuccessful HTTP response: a status outside 2xx,
// with the body and headers it arrived with.
//
// Error renders "<Endpoint>: <StatusCode> <Message> (request_id=<id>)", each
// part left out when it is empty or absent, as the Python SDK's str() of
// TypeSafeAPIError does. The SDK builds Message from the body the way the
// Python SDK finds a message in it (the "error", "message" and "detail"
// members, or the body itself), escaped and cut at 200 characters; a message
// the caller sets is printed as it is.
type APIError = engine.APIError

// APIErrorAuthentication is status 401: authentication failed.
const APIErrorAuthentication APIErrorKind = engine.APIErrorAuthentication

// APIErrorBadRequest is status 400: the request was invalid.
const APIErrorBadRequest APIErrorKind = engine.APIErrorBadRequest

// APIErrorInternalServer is any status from 500 up: the server failed.
const APIErrorInternalServer APIErrorKind = engine.APIErrorInternalServer

// APIErrorKind classifies an unsuccessful response by its status, as the
// Python SDK's subclasses of TypeSafeAPIError do. The mapping is by status
// alone, so a documented status with an undocumented body still lands in its
// class.
type APIErrorKind = engine.APIErrorKind

// APIErrorNotFound is status 404: the resource was not found.
const APIErrorNotFound APIErrorKind = engine.APIErrorNotFound

// APIErrorOther is any status without a class of its own: 408, 409 or a
// redirect the transport did not follow, for example.
const APIErrorOther APIErrorKind = engine.APIErrorOther

// APIErrorPermissionDenied is status 403: access was denied. The API
// also answers a request without a key with 403; see
// [APIError.IsAuthentication].
const APIErrorPermissionDenied APIErrorKind = engine.APIErrorPermissionDenied

// APIErrorRateLimit is status 429: the rate limit was exceeded.
const APIErrorRateLimit APIErrorKind = engine.APIErrorRateLimit

// APIErrorUnprocessableEntity is status 422: the request failed the
// server's validation.
const APIErrorUnprocessableEntity APIErrorKind = engine.APIErrorUnprocessableEntity

// APIKeyEnv names the variable holding the API key.
const APIKeyEnv = engine.APIKeyEnv

// Answer is one answer of any kind: Kind says which of Noul, Choice and
// Score holds it.
type Answer = engine.Answer

// AnswerKind is the kind of question an answer belongs to, which the answer's
// "type" member names on the wire.
type AnswerKind = engine.AnswerKind

// Answers is the answers of one response, keyed by the question names. It
// reads as the Python SDK's answers dict: a name the response repeats keeps
// the position where it first appeared and the value of its last
// appearance, and an answer of a type this version does not model is not
// there (it stays in the raw body, [ResponseMeta.RawBody]). The Python SDK's
// nouls, choices and scores views are the Nouls, Choices and Scores
// iterators.
//
// An Answers is a view of its response: it is valid as long as the response
// is, it shows the new answers after the response's UnmarshalJSON, and every
// value it yields is a copy that shares the response's slices and bytes,
// which must not be modified. The zero Answers is empty.
type Answers = engine.Answers

// Ask asks the questions the struct type T declares about state and returns
// the answers as a T: it is [Client.SystemOne] with the question set
// [PreparedFor] builds for T, followed by [DecodeAs] of the response.
//
//	t, err := typesafe.Ask[Ticket](ctx, c, state)
//
// A T that PreparedFor refuses fails with its [*ConfigError] before any
// request is made. Every error of the call itself, an [*APIError], a
// [*ConnectionError], a [*TimeoutError], a [*ResponseValidationError] of the
// response as a whole and the others [Client.SystemOne] lists, is returned
// as SystemOne returns it. A response whose answers do not fit T fails as
// DecodeAs says, with the call's endpoint in the error and its header
// redacted as the call's other errors redact theirs: by the header's name,
// and a header whose value holds the client's API key.
//
// Ask returns only the answers. A caller that also needs the response,
// its request id, usage, model or raw body, makes the two calls Ask makes:
//
//	qs, err := typesafe.PreparedFor[Ticket]()
//	resp, err := c.SystemOne(ctx, state, qs)
//	t, err := typesafe.DecodeAs[Ticket](resp)
//	id, ok := resp.Meta().RequestID()
func Ask[T any](ctx context.Context, c *Client, state any, opts ...CallOption) (T, error) {
	return engine.Ask[T](ctx, c, state, opts...)
}

// BaseURLEnv names the variable holding the API base URL.
const BaseURLEnv = engine.BaseURLEnv

// CallOption configures one call, over the client's settings: [Model],
// [Timeout], [Header], [ExtraBody] and [Retry]. As with [ClientOption], an
// option only records its setting; the call checks them all before it
// encodes or sends anything and reports the first it cannot use as a
// [*ConfigError], in a fixed order whatever the order of the options: a
// System One call checks the model, then the timeout, the retry policy and
// the headers; a list-models call first refuses Model and ExtraBody, then
// checks the timeout, the retry policy and the headers. Among options of one
// kind the last one wins, except that every [Header] and every [ExtraBody]
// counts. A nil CallOption is ignored.
type CallOption = engine.CallOption

// Choice is a question that picks one of a set of named options. See
// https://docs.typesafe.ai/primitives/choice.
type Choice = engine.Choice

// ChoiceAnswer is the answer to a choice question: the option picked and the
// probability of every option. See the choice primitive
// (https://docs.typesafe.ai/primitives/choice).
//
// The zero ChoiceAnswer is not an answer a response carried: its Present is
// false, and MarshalJSON writes it null. [DecodeAs] leaves one in an
// optional field whose answer is absent.
type ChoiceAnswer = engine.ChoiceAnswer

// Client calls the TypeSafe API. It is safe for concurrent use by multiple
// goroutines; build it with [NewClient] and release its connections with
// [Client.Close]. The zero Client is not usable.
//
// The first attempt of every call hands the transport the client's own
// header map, shared by every call and never copied, so a RoundTripper
// given with [WithRoundTripper] must not modify a request, as the
// [net/http.RoundTripper] contract already requires.
type Client = engine.Client

// ClientOption configures a client.
//
// An option only records its setting; the client checks every setting
// together when it is built and reports the first one it cannot use as a
// [*ConfigError], before anything is sent. So the order of options of
// different kinds never decides whether a set of them is accepted. Among
// options of one kind the last one wins and is the only one checked:
// WithTimeout(0) followed by WithTimeout(time.Second) is accepted, the
// reverse is not. [WithHeader] keeps the last value per header name, and
// checks every call. A nil ClientOption is ignored.
//
// A setting that no option gives is read from its environment variable
// ([APIKeyEnv], [BaseURLEnv], [DefaultModelEnv]), trimmed of leading and
// trailing whitespace; a variable that is unset or blank counts as unset, and
// the SDK's default ([DefaultBaseURL], [DefaultModel]) applies. An option
// always wins over the environment, even when its value is unusable: the
// environment is not consulted for a setting an option gave.
type ClientOption = engine.ClientOption

// ConfigError reports something the caller configured that the SDK cannot
// use: a [ClientOption] that fails when the client is built (a missing or
// malformed API key, the base URL, the model, a timeout, a header name or
// value, the User-Agent product), or a question set that [Questions.Prepare]
// rejects. It is returned before any request is sent, and retrying cannot fix
// it.
//
// Error returns the message, which names what is wrong without repeating a
// credential: neither the API key nor the value of a header the caller set is
// ever part of it. Unwrap returns the
// errors it wraps, if any. A rejected question set wraps the failure behind
// the message, such as the syntax error in JSON content; its type is
// internal to the SDK, so only its text, which the message already carries,
// is of use to a caller. A condition a caller may want to branch on is
// wrapped as a sentinel error that the function returning it documents.
type ConfigError = engine.ConfigError

// ConnectionError reports a request that produced no HTTP response: the
// connection could not be made, failed or was lost, or a proxy refused it.
// Retrying may help.
//
// Error returns "Connection error: <cause>", the cause's text escaped, cut
// at 200 characters and with any credential of the request replaced. Unwrap
// returns the transport's error, unless it, or an error it wraps, showed a
// credential of the request in its text, its %+v or its %#v: then it
// returns a stand-in whose text has the credentials replaced and which
// unwraps only to the well-known errors the transport's error matched, such
// as [context.DeadlineExceeded], [io.ErrUnexpectedEOF] or a
// [syscall.Errno]. An error that points to the request, which only a
// caller's RoundTripper, dialer or response body can return, is kept, and
// errors.As reaches the caller's own request through it.
type ConnectionError = engine.ConnectionError

// Content is text, or a JSON object or array: what the API accepts as a
// question's instructions, as the description of an outcome or an option,
// and as a score level.
//
// Build it with [Text] or [JSON]. The zero Content is unset: an optional
// member holding it is left off the wire, as the Python SDK leaves off an
// optional member that is None.
type Content = engine.Content

// DecodeAs returns the answers of resp as a T, the struct type whose fields
// declare the questions ([PreparedFor] has the grammar): each answer field
// holds the answer that resp carries under the field's question name.
// resp may answer a question set built by hand, such as one from
// [NewQuestions]; the names are what DecodeAs matches, so a field tagged
// name=spam reads the answer to the question "spam".
//
// DecodeAs reads the answers as [SystemOneResponse.Answers] holds them:
// when the body repeats a name, the last answer under it is the one read,
// and an answer of a type this version does not model is not there. The
// fields hold copies that share resp's slices and bytes, which must not be
// modified; resp itself is not changed, and must not be nil. Answers that
// no field of T names are ignored. Each field read has Present true; an
// optional field without an answer is left as the zero answer, whose
// Present is false and which marshals as null, as the Python SDK holds and
// dumps None there.
//
// A T that PreparedFor refuses fails with its [*ConfigError]. Otherwise the
// fields are read in their order in T, and the first that does not fit
// fails the whole decode: DecodeAs returns the zero T, never one holding
// the fields read before the failure, and a [*ResponseValidationError]
// whose FieldPath names the answer. T's fields are the answers lifted out
// of the response's "answers" member, so the paths are the ones the Python
// SDK reports for such a response model, a SystemOneResponse subclass with
// one field per answer (the upstream tests' TypedSystemOneResponse): the
// answer's name, then the member and the key. An answer of a type this
// version does not model has been skipped, as that model skips it, so under
// a required field's name it fails as absent and under an optional field's
// name it leaves the field absent, and a response without an "answers"
// member fails at T's first required field:
//
//	the answer is absent and the field is not optional  <name>
//	the answer is of another kind than the field        <name>.type
//	a choice picks an option T does not list            <name>.choice
//	a choice gives a probability to such an option      <name>.probabilities.<option>
//	a score's legend has a level beyond T's levels      <name>.legend.<level>
//	a score gives a probability to such a level         <name>.probabilities.<level>
//
// A failure of the response as a whole, a missing model or usage or an
// answer without a type, comes from the decoder before T is filled, at the
// decoder's own path, such as usage or answers.spam.noul, as in Python,
// which validates the base model's fields first.
//
// A choice's options and a score's levels are the ones T's tag lists: a
// level counts from zero, so a score with three levels has the levels 0, 1
// and 2, and a level is written in decimal in the path. An option or a
// level the answer does not mention, and the score's value, are not
// checked. Python checks an option only when the response model's own type
// says so, with a Literal, and then reports the pick at "tone.choice", as
// DecodeAs does.
//
// The error carries resp's HTTP metadata: its status, header, request id
// and body when resp came from a request, and none of them when it was read
// back with [SystemOneResponse.UnmarshalJSON], whose Meta is empty. Its
// Header is a new map in which each value of a header that is a credential
// by its name, such as Authorization, Cookie or Set-Cookie
// ([APIError.Header] lists them), is "***"; the other headers' values are
// the response's own and must not be modified. DecodeAs has no client, so
// unlike [Ask] it cannot look for the client's API key: a key the server
// echoes in another header or in the request id stays visible in Header
// and Error, where Ask shows "***". Neither redacts FieldPath: the answer's
// name and the option or level it names are shown as they arrived, as the
// SDK's other errors show a path (ruling R103-rev). Its Endpoint is empty;
// Ask fills it in.
func DecodeAs[T any](resp *SystemOneResponse) (T, error) {
	return engine.DecodeAs[T](resp)
}

// DefaultBaseURL is the API base URL.
const DefaultBaseURL = engine.DefaultBaseURL

// DefaultConnectTimeout is the deadline for opening a connection,
// inside the deadline of the attempt that opens it.
const DefaultConnectTimeout time.Duration = engine.DefaultConnectTimeout

// DefaultMaxResponseBytes is the largest response body a request reads:
// 16 MiB.
const DefaultMaxResponseBytes = engine.DefaultMaxResponseBytes

// DefaultModel is the model a request names when the call names none.
const DefaultModel = engine.DefaultModel

// DefaultModelEnv names the variable holding the model a request names
// when the call names none.
const DefaultModelEnv = engine.DefaultModelEnv

// DefaultRetry returns the policy a client uses unless [WithRetry] sets
// another, as the Python SDK uses RetryPolicy() when its retry argument is
// None: 2 retries, a backoff of 500 ms doubling up to 5 s with a jitter of
// 0.25, the statuses 408, 429 and 500 to 599, Retry-After honoured,
// connection and timeout errors retried, and a budget of 30 s. It is the
// zero RetryPolicy.
func DefaultRetry() RetryPolicy {
	return engine.DefaultRetry()
}

// DefaultTimeout is the deadline of each attempt of a request.
const DefaultTimeout time.Duration = engine.DefaultTimeout

// ErrClientClosed reports a call on a client that was closed. The SDK
// returns it wrapped in a [*ConfigError]: errors.Is(err, ErrClientClosed)
// tells it apart.
var ErrClientClosed = engine.ErrClientClosed

// ErrHTTP2NotNegotiated reports that the API host did not speak HTTP/2
// under [HTTP2Only]: its TLS handshake chose another protocol or none, it
// refused h2, a caller TLS dialer returned a connection without h2, or a
// response came back over HTTP/1.1. The SDK returns it wrapped in a
// [*ConfigError], which retrying cannot fix: errors.Is(err,
// ErrHTTP2NotNegotiated) tells it apart. [HTTPAuto] allows HTTP/1.1.
var ErrHTTP2NotNegotiated = engine.ErrHTTP2NotNegotiated

// Error is implemented by every error the SDK returns, and only by them:
// [*APIError], [*ConnectionError], [*TimeoutError],
// [*ResponseValidationError], [*ResponseTooLargeError], [*ConfigError] and
// [*InvalidRequestError]. Each is a distinct type that [errors.As] matches,
// and errors.As with a *typesafe.Error target matches any of them, as the
// Python SDK's TypeSafeError base class does. The one exception is a
// cancellation: a call whose context is cancelled returns ctx.Err()
// ([context.Canceled]) itself, as the Python SDK lets
// asyncio.CancelledError through.
//
// An SDK error is a value: where the Python SDK copies, pickles and rebuilds
// its exceptions (to send one to another process, say), a Go caller copies
// the struct an error points to (c := *e) and uses &c, which renders, reads
// and unwraps as the original does and shares its Header and Body. The
// struct value c is not itself an error, and fmt prints its fields, so print
// &c, never c. A caller may also hand the pointer to another goroutine,
// since no read of an error changes it. [errors.As] with a pointer to one of
// the seven types, or with a *Error, finds the error through any wrapping and
// returns the very pointer. Nothing is serialised.
//
// No error's text holds the API key, a request's state or a response body
// unescaped: text the SDK did not write is escaped and cut (the server's
// message at 200 characters, a name the server chose at 128, a field path
// at 320).
type Error = engine.Error

// ExtraBody adds the member key with value v to the top level of this System
// One call's request body, as the Python SDK's extra_body does: a key named
// "state", "model" or "questions" replaces that member's value where it
// stands (the replaced value is not encoded at all), any other key is
// appended in the order the options first name it, and a key given twice
// sends its last value. List-models calls have no body and refuse this
// option.
//
// v may be any value JSON can hold, encoded as the call's state is: a
// [RawJSON] is sent as it is after a check of its first byte, a [Content]
// as a question sends it (unset Content as null), a nil as null, and
// anything else by the JSON encoder, with the float spelling and map order
// that [Client.SystemOne] describes for the state. A value JSON has no form
// for, or a plain []byte (whose intent is ambiguous: send string(b) or
// RawJSON(b)), makes the call fail with an [*InvalidRequestError] before
// anything is sent.
//
// An extra "state" follows the rules of the state, so a nil, a number or a
// boolean is refused where typesafe-sdk-python sends it; an extra
// "questions" of nil is sent as null.
func ExtraBody(key string, v any) CallOption {
	return engine.ExtraBody(key, v)
}

// HTTP2Only speaks HTTP/2 alone, on one connection per API host: ALPN
// must choose h2 on https, and http uses HTTP/2 with prior knowledge. An
// API host that does not negotiate HTTP/2 is refused with a
// [*ConfigError] wrapping [ErrHTTP2NotNegotiated], before any byte of
// the request is sent. It is the default for an https base URL.
const HTTP2Only HTTPVersion = engine.HTTP2Only

// HTTPAuto lets ALPN choose between HTTP/2 and HTTP/1.1 (HTTP/1.1 on
// http), with no ALPN refusal and no cap on connections; a cold start
// still dials once before the requests waiting on it go out. It is the
// default for an http base URL.
const HTTPAuto HTTPVersion = engine.HTTPAuto

// HTTPVersion is the HTTP version policy of a client's transport
// ([WithHTTPVersion]). Its zero value is not a policy.
type HTTPVersion = engine.HTTPVersion

// Header sets a header this call sends, over the client's: it replaces a
// [WithHeader] of the same name, compared without regard to case, as a
// per-call header replaces a default one in typesafe-sdk-python
// (py:_core/transport.py:117), and a later Header of the same name replaces
// an earlier one.
//
// The rules of WithHeader apply: the SDK's own headers and the transport's
// win, and a caller's value of any of them is dropped and logged at
// [slog.LevelDebug] by name; X-TypeSafe-Retry-Count, which the SDK sets on
// retries only, is dropped too (py:_core/transport.py:118).
//
// The name must be a valid HTTP field name and the value a valid field
// value. A name that contains the API key is refused, when the key is at
// least 8 bytes long (ruling R68). Each of these failures fails the call
// before anything is sent, and no error repeats a value.
func Header(name string, value string) CallOption {
	return engine.Header(name, value)
}

// InvalidRequestError reports a request the SDK refuses to send because the
// API cannot accept it or its body cannot be written as JSON: a state that
// is not text, a JSON object or an array (nil, a number, a boolean); a
// plain []byte, whose intent is ambiguous (send string(b) for text or
// RawJSON(b) for JSON); text that is not valid UTF-8; or a value JSON has no
// form for, such as NaN, a channel or a cyclic structure. It is returned
// before any request is sent, and retrying the same request cannot fix it.
// A request the server itself refuses, with status 400 or 422 for example,
// is an [*APIError] instead.
//
// Error returns the message; the part of it that quotes the encoder is
// escaped and cut at 200 characters, so it never carries the state. Unwrap
// returns the cause. When the encoder failed, the chain continues to the
// encoder's own error, and through it to the error a caller's MarshalJSON
// method returned, which [errors.Is] and [errors.As] reach; the encoder's
// own error types are not part of the SDK's API and may change with it.
type InvalidRequestError = engine.InvalidRequestError

// JSON returns content that is the JSON object or array raw, such as
// JSON([]byte(`{"subject":"refund","amount":20}`)) or a [RawJSON] value.
//
// raw is kept, not copied, until [Questions.Prepare] checks it and writes it
// without its insignificant whitespace; the caller must not modify it in
// between. Anything but a single JSON object or array, with optional
// whitespace around it, makes Prepare fail with a [*ConfigError]; text is
// built with [Text], never from a JSON string. As with [RawJSON], a repeated
// member name inside an object is passed through for the server to decide.
func JSON(raw []byte) Content {
	return engine.JSON(raw)
}

// KindChoice is a choice answer, a [ChoiceAnswer] ("type": "choice").
const KindChoice AnswerKind = engine.KindChoice

// KindNoul is a yes/no answer, a [NoulAnswer] ("type": "noul").
const KindNoul AnswerKind = engine.KindNoul

// KindScore is a score answer, a [ScoreAnswer] ("type": "score").
const KindScore AnswerKind = engine.KindScore

// LevelTrace is the log level of the records that carry request and response
// bodies, below [slog.LevelDebug]: a body holds the caller's state, which
// may be personal data, so a handler shows it only when set to this level
// or lower. typesafe-sdk-python logs bodies at DEBUG.
const LevelTrace slog.Level = engine.LevelTrace

// Model sets the model this System One call names, in place of the client's
// ([WithModel]). The model is sent as given; an empty or blank model is
// refused rather than sent, and so is one that is not valid UTF-8. An
// [ExtraBody] member named "model" replaces it in the body. List-models calls
// name no model and refuse this option.
func Model(name string) CallOption {
	return engine.Model(name)
}

// ModelCard describes one model the account can use.
type ModelCard = engine.ModelCard

// Models is the list-models endpoint of a client, from [Client.Models].
type Models = engine.Models

// ModelsResponse is the response to a list-models call: the models the
// account can use, with the HTTP response they came in.
//
// It is immutable, except that [ModelsResponse.UnmarshalJSON] replaces the
// whole response in place: no other goroutine may read the response during
// the call, and a slice Models returned before it, or a copy of the
// response made before it, keeps the old cards.
type ModelsResponse = engine.ModelsResponse

// NewClient builds a client from opts. Unless an option supplies the
// transport ([WithHTTPTransport], [WithRoundTripper]), the client builds its
// own: HTTP/2 on one connection per client for an https base URL (HTTP/1.1
// or HTTP/2 for http; [WithHTTPVersion]), through the proxy the environment
// names ([WithProxy]). Every option is checked before the client is built,
// and the first that cannot be used is reported as a [*ConfigError];
// nothing is sent.
func NewClient(opts ...ClientOption) (*Client, error) {
	return engine.NewClient(opts...)
}

// NewQuestions returns an empty question set.
func NewQuestions() *Questions {
	return engine.NewQuestions()
}

// NoRetry returns the policy that never tries a call again: every call makes
// exactly one attempt, as the Python SDK's RetryPolicy(max_retries=0) does.
// It is DefaultRetry().MaxRetries(0).
func NoRetry() RetryPolicy {
	return engine.NoRetry()
}

// Noul is a yes/no question: how true is a statement about the state? See
// https://docs.typesafe.ai/primitives/noul.
//
// Every member is optional; an unset one is left off the wire. Yes and No
// describe what counts as each outcome and are sent as the "criteria"
// object's "true" and "false" members; "criteria" is left off when both are
// unset. The Python SDK can also send an empty "criteria" object or a null
// outcome, which mean the same as leaving them out; a [RawQuestion] sends
// those shapes when they are wanted.
type Noul = engine.Noul

// NoulAnswer is the answer to a yes/no question. See the noul primitive
// (https://docs.typesafe.ai/primitives/noul).
//
// The zero NoulAnswer is not an answer a response carried: its Present is
// false, and MarshalJSON writes it null. [DecodeAs] leaves one in an
// optional field whose answer is absent.
type NoulAnswer = engine.NoulAnswer

// Option is one option of a [Choice].
type Option = engine.Option

// Options lists the options of a [Choice] in the order they are sent.
type Options = engine.Options

// Prepared is a question set validated and serialised once by
// [Questions.Prepare], and reused as is by every call that asks it.
//
// It is read-only and safe for concurrent use. It holds, besides the bytes a
// request sends as "questions", the tables the response decoder matches
// answers against: the names, each choice question's option labels and each
// score question's levels.
type Prepared = engine.Prepared

// PreparedFor returns the question set that the struct type T declares: one
// question per answer field, in field order, prepared as [Questions.Prepare]
// prepares a set built by hand.
//
// An answer field is an exported field of type [NoulAnswer], [ChoiceAnswer]
// or [ScoreAnswer] whose struct tag has a "typesafe" key describing the
// question it answers:
//
//	type Ticket struct {
//		Billing typesafe.NoulAnswer   `typesafe:"kind=noul;instructions=Is this about billing, invoices or refunds?;yes=payments or invoices"`
//		Tone    typesafe.ChoiceAnswer `typesafe:"kind=choice;instructions=What is the tone?;options=calm=neutral or polite|angry"`
//		Urgency typesafe.ScoreAnswer  `typesafe:"kind=score;instructions=How urgent?;levels=can wait|this week|today"`
//		Spam    typesafe.NoulAnswer   `typesafe:"kind=noul;optional;instructions=Spam?"`
//	}
//
// PreparedFor[Ticket] asks the same four questions, with the same bytes on
// the wire, as
//
//	typesafe.NewQuestions().
//		Noul("Billing", typesafe.Noul{Instructions: typesafe.Text("Is this about billing, invoices or refunds?"), Yes: typesafe.Text("payments or invoices")}).
//		Choice("Tone", typesafe.Choice{Instructions: typesafe.Text("What is the tone?"), Options: typesafe.Options{{Label: "calm", Description: typesafe.Text("neutral or polite")}, {Label: "angry"}}}).
//		Score("Urgency", typesafe.Score{Instructions: typesafe.Text("How urgent?"), Levels: []typesafe.Content{typesafe.Text("can wait"), typesafe.Text("this week"), typesafe.Text("today")}}).
//		Noul("Spam", typesafe.Noul{Instructions: typesafe.Text("Spam?")}).
//		Prepare()
//
// # Tag grammar
//
// The tag is a list of entries separated by ";". An entry is a key, "=" and
// a value, or the bare key optional. The keys are:
//
//   - kind (required): noul, choice or score; it must agree with the field's
//     type (kind=noul for a NoulAnswer field, and so on).
//   - name: the name the question is asked under and its answer comes back
//     under. Without it the name is the field's name as written, Billing for
//     the field Billing: nothing is lowercased or converted, as encoding/json
//     does with an untagged field. The names type, model, usage and answers
//     are reserved.
//   - instructions: the question's instructions, for every kind.
//   - yes, no: what counts as a yes and as a no answer (kind=noul only), the
//     [Noul] members of the same names.
//   - options: the options of a choice (kind=choice only, and required
//     there), separated by "|", in order. An option is a label, or a label,
//     "=" and its description: options=calm=neutral or polite|angry. Labels
//     must be unique.
//   - levels: the levels of a score (kind=score only, and required there),
//     separated by "|", lowest first. Levels must be unique.
//   - optional: the answer may be absent from a response. It changes
//     nothing on the wire; it tells the typed decoder to leave the field's
//     Present false instead of failing when the answer is missing.
//
// Every value is text, sent as [Text] content; JSON content is written with
// [Questions] instead. A value may contain any character, but four must be
// escaped where they would otherwise end something: "\;" is a ";", "\|" a
// "|", "\=" a "=" and "\\" a backslash. A ";" always ends the entry, so it is
// escaped in every value. A "|" ends an option or a level, so it is escaped
// in every option and level, descriptions included:
// options=calm=neutral|polite|angry asks three options, calm, polite and
// angry, where options=calm=neutral\|polite|angry asks two. The first "=" of
// an option ends its label, and a later "=" belongs to the description. In
// instructions, name, yes and no, "|" and "=" stand for themselves, and in a
// level "=" does; escaping them there is allowed but not needed. No other
// escape exists, keys are never escaped, and no space is trimmed.
//
// These are errors: an unknown key, a key given twice, a key the kind does
// not take (yes and no belong to noul, options to choice, levels to score),
// an empty value, an empty entry (";;", or a ";" at either end), an empty
// option, level, label or description, a backslash before any other
// character, a backslash at the end of the tag, and a tag that is not valid
// UTF-8.
//
// A struct tag is itself a Go string literal, so in source each of these
// backslashes is written twice: `typesafe:"kind=noul;instructions=a\\;b"`
// asks "a;b". A single backslash makes the tag malformed (go vet reports it),
// and PreparedFor refuses the field instead of ignoring the tag, as it does
// when the key is written with a space around its colon, is given twice, or
// follows a malformed pair: every tag that reflect would read as having no
// typesafe key, or only the first of two, while it names one.
//
// # Rejections
//
// PreparedFor fails with a [*ConfigError] that names T, the field and the
// rule when:
//
//   - two fields ask under the same name;
//   - a choice has no options, or lists an option label twice (a choice built
//     with [Questions] may have none: its empty criteria are sent for the
//     server to judge);
//   - a score lists a level twice;
//   - a score has no levels;
//   - an answer field's tag has no kind, or the field has no tag at all;
//   - the kind is not noul, choice or score;
//   - the kind does not agree with the field's type, or a field that is not
//     an answer field has a typesafe tag;
//   - a field is a pointer to an answer type (write optional instead);
//   - an unexported field has a typesafe tag;
//   - a struct-typed field, embedded or named, value or pointer, holds a
//     field with a typesafe tag at any depth: the fields of a nested struct
//     are not read, and an embedded struct's are not promoted;
//   - T is not a struct type (a pointer to a struct included);
//   - a question name is reserved;
//   - optional is given on a field that is not an answer field;
//   - the tag does not follow the grammar above;
//   - T has no answer fields: "At least one question is required.", as
//     [Questions.Prepare] reports for an empty set.
//
// Fields that are neither answer fields nor tagged, and unexported fields
// without a typesafe tag, are ignored. Fields of an embedded struct are not
// promoted, and those of a named struct-typed field are not read: only T's
// own fields are, so a struct-typed field whose type holds typesafe tags is
// refused rather than silently skipped, and one without such tags is
// ignored like any other untagged field. A type alias of
// an answer type is that answer type; a type defined from one is not an
// answer type.
//
// # Caching
//
// T is inspected once: the first call builds the set, or the error, and every
// later call for the same T returns that same *Prepared, or that same error,
// for the life of the process, without allocating. The set is read-only and
// safe for concurrent use, like every prepared set; concurrent first calls
// may build it more than once, but all of them return the one that was kept.
func PreparedFor[T any]() (*Prepared, error) {
	return engine.PreparedFor[T]()
}

// Questions is a question set under construction: the questions of one call,
// keyed by the names their answers come back under, in the order they are
// sent.
//
// Nothing is checked until [Questions.Prepare], which validates and
// serialises the whole set once. The zero Questions is an empty set ready to
// use.
//
// Adding a question copies the question value: a later change to the Noul,
// Choice, Score or RawQuestion variable that was added, such as assigning
// its Instructions, does not reach the set. The copy shares what the value
// refers to: the Options and Levels slices, the Fields map and the maps and
// slices inside it, and the bytes behind [JSON] content and [RawJSON]. Those
// are read by Prepare and must not change between adding the question and
// the return of Prepare; the prepared set shares none of them.
type Questions = engine.Questions

// RawJSON is one JSON value that is already encoded. The SDK never decodes
// it: strings keep their escape sequences and numbers their spelling. That
// makes it the way to send a number spelled exactly: a float in a state that
// is not RawJSON is written as Go's JSON encoders spell it, 3 for 3.0 and
// 10000000000000000 for 1e16, where the Python SDK writes 3.0 and 1e+16.
//
// As a [RawQuestion] field value it is checked and written without its
// insignificant whitespace, as the value it holds; [JSON] takes one to build
// structured [Content]. As the state of a call, or as the value of a member
// the call adds to the request body, it is sent as it is, whitespace
// included, after a check of its first byte only: a state must start a
// string, an array or an object, a member any JSON value. That it is one
// valid JSON value is then the caller's contract. A *RawJSON there is sent
// as the RawJSON it points to; a nil one is refused. Nested inside a state
// or a member's value (a map value, a struct field, a slice element, through
// a pointer too), it is written by [RawJSON.MarshalJSON]: checked and written
// without its insignificant whitespace, as a question field is. A member name
// repeated inside an object (`{"a":1,"a":2}`) is passed through unchanged,
// which a Python dict cannot produce; the server decides which one counts.
type RawJSON = engine.RawJSON

// RawQuestion is a question of a type, or with members, that this version of
// the SDK does not model, sent as a JSON object: "type" first, then Fields in
// sorted key order.
//
// Type must not be empty, and Fields must not name "type". A field value is
// nil, a bool, a string, an integer or float kind (a float must be finite, and
// is spelled as the Python SDK spells it: 3.0, 0.00001, 1e-6, 1e+16), []any,
// []string, map[string]any, map[string]string, [Content] (unset Content is
// null) or [RawJSON], nested in maps and slices to any depth up to 1000
// levels. Map members are sent in sorted key order, as a Go map has no order
// of its own. A value of any other type, such as []int, a named string type or
// a struct, makes Prepare fail: encode it first and pass the bytes as
// [RawJSON], which is checked and sent without its insignificant whitespace
// but never decoded.
//
// [Questions.Prepare] applies the checks the Python SDK applies to a raw
// question: a "choice" or "score" has a "criteria" field, and a "score"'s
// criteria is not empty (not null, false, 0, "", [] or {}). Everything else
// is left to the server.
type RawQuestion = engine.RawQuestion

// ResponseMeta is the HTTP side of a response, the Python SDK's
// raw_http_response: the status, the header and the body exactly as they
// arrived. The header and the body are shared with the response, not
// copied, and must not be modified. A response that did not come from a
// request, such as one read back from JSON, has an empty ResponseMeta.
//
// It is HTTP metadata, not part of the response's payload: a response's
// MarshalJSON leaves it out, and it has no MarshalJSON of its own.
type ResponseMeta = engine.ResponseMeta

// ResponseTooLargeError reports a successful response whose body is larger
// than the client's size limit (16 MiB unless configured otherwise): the
// body was not read past the limit and nothing was decoded. Retrying the
// same request cannot help. A failure status with a body over the limit is
// an [*APIError] with an empty body instead, which keeps its status and
// headers.
type ResponseTooLargeError = engine.ResponseTooLargeError

// ResponseValidationError reports a successful response whose body is not
// the response the SDK expected: not one JSON object, not valid UTF-8, a
// raw control character in a string, data after the object, nesting past
// the codec's 4096 levels, or a member that is missing or of the wrong
// kind. FieldPath names the first failure the Python SDK would report.
//
// Error renders "<Endpoint>: <StatusCode> Invalid response data at
// '<FieldPath>'. (request_id=<id>)", as the Python SDK's str() of
// TypeSafeAPIResponseValidationError does. Unwrap returns the decoder's
// failure, whose type is internal to the SDK. A failure of a typed decode
// ([DecodeAs], [Ask]) names FieldPath as the Python SDK's response model
// with one field per answer names it, such as "tone.choice", while the
// failure it wraps keeps the answer's place in the body,
// "answers.tone.choice" (ruling R99-rev).
type ResponseValidationError = engine.ResponseValidationError

// Retry sets the retry policy of this call, in place of the client's
// ([WithRetry]), as a whole: no setting of the client's policy carries over.
// [NoRetry] makes the call a single attempt. A policy with a setting out of
// range fails the call with a [*ConfigError], before anything is sent
// ([RetryPolicy]).
func Retry(policy RetryPolicy) CallOption {
	return engine.Retry(policy)
}

// RetryPolicy decides whether a call makes another attempt after one fails,
// and how long it waits first, as typesafe-sdk-python's RetryPolicy does
// (py:_core/retry.py). A policy is a value: each setter returns a copy with
// one setting changed, so a policy can be shared by goroutines and derived
// from freely. [WithRetry] sets a client's policy and [Retry] one call's.
//
// The zero RetryPolicy is [DefaultRetry], the Python SDK's RetryPolicy():
//
//   - at most 2 retries after the first attempt ([RetryPolicy.MaxRetries]);
//   - a wait that starts at 500 ms, doubles with each retry up to 5 s, and
//     loses a random fraction of at most 25 % ([RetryPolicy.Backoff]);
//   - the statuses 408, 429 and 500 to 599 retried ([RetryPolicy.Statuses]);
//   - the server's Retry-After-Ms or Retry-After honoured
//     ([RetryPolicy.RespectRetryAfter]);
//   - a [*ConnectionError] and a [*TimeoutError] retried
//     ([RetryPolicy.ConnectionErrors], [RetryPolicy.TimeoutErrors]);
//   - a budget of 30 s per call ([RetryPolicy.Budget]).
//
// After an attempt fails, the call makes another when all of these hold, in
// the order tenacity, which the Python SDK runs its policy on, checks them
// (tenacity also computes the wait, drawing its jitter, before it counts
// the attempts; the Go loop draws the jitter only for a retry that may
// follow, which no caller can observe):
//
//   - The error is one the policy retries: a *TimeoutError or a
//     *ConnectionError of a kind it retries, an [*APIError] whose status is
//     in its set, or any error its predicate accepts
//     ([RetryPolicy.Predicate]). A successful (2xx) status is never retried
//     by status, even when the set holds it: such a response is billed, so a
//     [*ResponseValidationError] is retried only when the predicate accepts
//     it. A cancellation ([context.Canceled]) is never retried, whatever the
//     predicate says.
//   - Fewer than MaxRetries retries have been made.
//   - The budget allows the wait: the time since the call's first attempt
//     started, which is after the call's options were checked and its body
//     encoded, plus the wait is below the budget (tenacity's
//     stop_before_delay).
//
// The wait is the server's when the policy honours it and the failed
// response carries a Retry-After-Ms (milliseconds) or a Retry-After
// (seconds, or an HTTP date) that parses, whatever the response's status,
// as [APIError.RetryAfter] reads it; however long it is, only the budget
// refuses it. Otherwise it is the backoff.
//
// A retry sends the same body and headers as the first attempt, plus
// X-TypeSafe-Retry-Count with the number of attempts before it, and has a
// deadline of its own ([WithTimeout], [Timeout]). The wait ends early when
// the call's context is done: a cancellation returns ctx.Err(),
// [context.Canceled], itself, and a passed deadline a [*TimeoutError]
// without a timeout. A call that stops returns the error of its last
// attempt. The transport's own replay of a request inside one attempt (an
// HTTP/2 request the server refused or never processed) is neither a retry
// nor counted by [Stats], and runs inside that attempt's deadline.
//
// A setting out of range is kept in the value and reported when the policy
// is used: [NewClient] with [WithRetry], or a call with [Retry], fails with a
// [*ConfigError] that carries the Python SDK's message, before anything is
// sent. The messages name the Python SDK's parameters: max_retries is
// [RetryPolicy.MaxRetries]; backoff_initial, backoff_max and backoff_jitter
// are the arguments of [RetryPolicy.Backoff]; timeout is
// [RetryPolicy.Budget], and timeout=None is [RetryPolicy.NoBudget]. Its
// other parameters are http_statuses ([RetryPolicy.Statuses]),
// respect_retry_after ([RetryPolicy.RespectRetryAfter]),
// api_connection_error ([RetryPolicy.ConnectionErrors]), api_timeout_error
// ([RetryPolicy.TimeoutErrors]) and predicate ([RetryPolicy.Predicate]);
// exceptions has no counterpart. A duration cannot be NaN or infinite, where
// the Python SDK refuses such a number of seconds.
type RetryPolicy = engine.RetryPolicy

// Score is a question that rates the state on an ordered scale. See
// https://docs.typesafe.ai/primitives/score.
type Score = engine.Score

// ScoreAnswer is the answer to a score question: the expected score, the
// question's rubric as the response echoes it, and the probability of every
// level. Levels count from zero. See the score primitive
// (https://docs.typesafe.ai/primitives/score).
//
// The zero ScoreAnswer is not an answer a response carried: its Present is
// false, and MarshalJSON writes it null. [DecodeAs] leaves one in an
// optional field whose answer is absent.
type ScoreAnswer = engine.ScoreAnswer

// Stats counts what a client has done since it was built.
type Stats = engine.Stats

// SystemOneResponse is the response to a System One call: the model that
// answered, the token usage and the answers, with the HTTP response they
// came in. See System One (https://docs.typesafe.ai/concepts/system-one).
//
// It is immutable, except that [SystemOneResponse.UnmarshalJSON] replaces
// the whole response in place: an Answers view taken before the call shows
// the new answers, a copy of the response made before the call keeps the
// old ones, and no other goroutine may read the response during the
// call.
type SystemOneResponse = engine.SystemOneResponse

// Text returns content that is the text s. Text("") is set: it is sent as an
// empty string, unlike the zero Content.
func Text(s string) Content {
	return engine.Text(s)
}

// Timeout sets the deadline of each attempt of this call, in place of the
// client's ([WithTimeout], [WithNoTimeout]). It must be positive, as the
// Python SDK refuses a zero, negative or non-finite per-call timeout.
func Timeout(d time.Duration) CallOption {
	return engine.Timeout(d)
}

// TimeoutError reports a request attempt that did not complete within its
// deadline. Retrying may help. It is not a [*ConnectionError], which
// errors.As tells apart; the Python SDK's TypeSafeAPITimeoutError is a
// subclass of its connection error.
type TimeoutError = engine.TimeoutError

// Usage is the token usage a response reported. The API may leave either
// count out, which is not the same as a count of zero; a count cannot be
// negative, and a response that reports one is refused.
type Usage = engine.Usage

// Version is the version of this SDK. Every request names it in the
// User-Agent and X-TypeSafe-SDK headers as typesafe-sdk-go/<Version>.
const Version = engine.Version

// WithAPIKey sets the API key, sent as Authorization: Bearer <key>. Without
// it the key is read from [APIKeyEnv].
//
// The key is trimmed of leading and trailing whitespace as Python's
// str.strip() trims it; what is left must be printable ASCII without
// whitespace, and must not be empty (py:_core/config.py:26-33). A key given
// here that fails either rule is refused: the environment is not consulted
// in its place. No error repeats the key.
func WithAPIKey(key string) ClientOption {
	return engine.WithAPIKey(key)
}

// WithBaseURL sets the API base URL, such as https://api.typesafe.ai. Without
// it the URL is read from [BaseURLEnv], and [DefaultBaseURL] applies when that
// is unset.
//
// Trailing slashes are removed, and a path the URL keeps is a prefix of the
// API paths: https://example.test/prefix/ sends to
// https://example.test/prefix/v1/systemone. The URL must be an absolute http
// or https URL with a host, and without credentials, a query or a fragment;
// the API key is passed with [WithAPIKey] only. No error repeats the URL.
func WithBaseURL(rawURL string) ClientOption {
	return engine.WithBaseURL(rawURL)
}

// WithClientTrace sets the net/http/httptrace hooks every request of the
// client reports to; nil removes them. The hooks are copied when the option
// is applied and run after the SDK's own, and before those of a trace the
// call's context carries (httptrace.WithClientTrace).
//
// A hook that panics, whether given here or carried by the call's context,
// does not unwind through net/http, which calls some hooks with its own
// locks held or a stream reserved: the panic is recovered inside the hook
// and raised again, with the same value, from the call that made the
// request once net/http has returned (any response body is closed first). A
// hook that panics after the call has returned is recovered and logged at
// WARN.
//
// Hooks must return promptly. The SDK's own transport (the default one and
// [WithHTTPTransport]'s clone) lets one request at a time write its headers,
// and a request's hooks run while it holds that turn, the first request on
// a new connection until its response headers arrive: a hook that blocks,
// in GotConn for example, stalls every other call on the client until each
// call's own deadline, and without a bound under [WithNoTimeout]. The
// shield above covers a panic, not a hook that does not return.
func WithClientTrace(trace *httptrace.ClientTrace) ClientOption {
	return engine.WithClientTrace(trace)
}

// WithConnectTimeout sets the deadline for opening a connection, TCP and TLS
// together, inside the deadline of the attempt that opens it;
// [DefaultConnectTimeout] unless set. It must be positive.
func WithConnectTimeout(d time.Duration) ClientOption {
	return engine.WithConnectTimeout(d)
}

// WithHTTPTransport makes the client use a clone of t, which keeps t's
// dialers, TLS configuration and proxy; t itself is not used or changed,
// except that cloning runs t's own first-use setup as t's first request
// would. Where t leaves them zero, the SDK sets the protocols of the
// [HTTPVersion] policy, one connection per host under [HTTP2Only], the
// HTTP/2 ping timeouts and the TLS handshake timeout ([WithConnectTimeout]);
// under HTTP2Only it always sets strict HTTP/2 stream accounting
// (HTTP2Config.StrictMaxConcurrentRequests), checks ALPN on the API host's
// handshake, and checks a connection from t's TLS dialer for h2. The
// cold-start gate and the header-write token apply.
//
// It cannot be combined with [WithRoundTripper], [WithProxy], [WithRootCAs]
// or [WithTLSConfig]; [WithConnectTimeout] still applies to what the SDK
// sets. A nil t is refused.
func WithHTTPTransport(t *http.Transport) ClientOption {
	return engine.WithHTTPTransport(t)
}

// WithHTTPVersion sets the HTTP version policy: [HTTP2Only], the default for
// an https base URL, or [HTTPAuto], the default for an http one. Any other
// value is refused when the client is built.
func WithHTTPVersion(v HTTPVersion) ClientOption {
	return engine.WithHTTPVersion(v)
}

// WithHeader sets a header sent on every request. A later WithHeader of the
// same name, compared without regard to case, replaces an earlier one, as a
// per-call header replaces a default one in typesafe-sdk-python
// (py:_core/transport.py:117). Its default headers differ: a mapping that
// holds two spellings of one name, such as X-Team and x-team, sends both.
//
// The SDK's own headers always win, as they do in typesafe-sdk-python, which
// writes them over the caller's (py:_core/transport.py:116-127): a caller's
// Authorization, Accept, User-Agent, X-TypeSafe-SDK, X-TypeSafe-Runtime and
// Content-Type are dropped, and so is X-TypeSafe-Retry-Count, which the SDK
// sets on retries only (py:_core/transport.py:118). [WithUserAgentProduct]
// and [WithRuntimeHeader] are the only ways to change what User-Agent and
// X-TypeSafe-Runtime carry. The headers that frame a message or manage its
// connection belong to the transport and are dropped too: Content-Length,
// Transfer-Encoding, Connection, Proxy-Connection, Keep-Alive, Upgrade, TE,
// Trailer and Host. Each dropped header is logged at [slog.LevelDebug] by
// name, never with its value.
//
// The name must be a valid HTTP field name (RFC 9110, section 5.6.2) and the
// value a valid field value (RFC 9110, section 5.5), or the client is not
// built. A name that contains the API key, without regard to case, is
// refused too, as when the two arguments are swapped, provided the key is at
// least 8 bytes long: a shorter key, a test's dummy such as "test", occurs in
// ordinary names. No error repeats a value, which is where a caller puts a
// token, or a name that holds the key.
func WithHeader(name string, value string) ClientOption {
	return engine.WithHeader(name, value)
}

// WithLogEndpointHost sets whether log records name the full endpoint URL.
// The default is true; with false they name only the API path, /v1/systemone
// or /v1/models, without the scheme, the host or the base URL's path prefix.
// An error's text, written by the network stack (a dial or DNS error), still
// names the host, in the error and in the record that logs it.
func WithLogEndpointHost(log bool) ClientOption {
	return engine.WithLogEndpointHost(log)
}

// WithLogger sets the logger the client writes its records to. The default,
// and what a nil logger means, discards every record. The client never
// configures the logger's level: typesafe-sdk-python's TYPESAFE_LOG_LEVEL is
// not read.
func WithLogger(logger *slog.Logger) ClientOption {
	return engine.WithLogger(logger)
}

// WithMaxResponseBytes sets the largest response body a request reads, in
// bytes; [DefaultMaxResponseBytes] (16 MiB) unless set. It must be at least 1,
// since every response carries a body, and at most 1 GiB.
func WithMaxResponseBytes(n int64) ClientOption {
	return engine.WithMaxResponseBytes(n)
}

// WithModel sets the model a request names when the call names none. Without
// it the model is read from [DefaultModelEnv], and [DefaultModel] applies
// when that is unset.
//
// The model is sent as given, without trimming. An empty or blank model is
// refused rather than sent, where typesafe-sdk-python would send it.
func WithModel(model string) ClientOption {
	return engine.WithModel(model)
}

// WithNoTimeout removes the deadline of each attempt: an attempt then ends
// when its response is read, when the call's context is done, or when the
// connection fails. It cannot be used together with [WithTimeout].
func WithNoTimeout() ClientOption {
	return engine.WithNoTimeout()
}

// WithPretouch prepares the JSON encoder for each type before the first
// call that encodes a state or an extra body value of it, so that the call
// does not pay the one-time compilation the encoder makes per type (which
// grows with the type's size). It changes nothing on the wire. The types are
// prepared when the client is built, after every other option is checked;
// a nil type, or one the encoder refuses (a map whose keys cannot be JSON
// object keys, for example), fails NewClient with a [*ConfigError]. Types
// from several WithPretouch options are all prepared.
func WithPretouch(types ...reflect.Type) ClientOption {
	return engine.WithPretouch(types...)
}

// WithProxy sets the func that chooses a proxy for each request, as
// http.Transport.Proxy does. The default is http.ProxyFromEnvironment
// (HTTPS_PROXY, HTTP_PROXY, NO_PROXY); nil disables proxies. It configures
// the SDK's own transport, so it cannot be combined with [WithHTTPTransport]
// or [WithRoundTripper].
func WithProxy(proxy func(*http.Request) (*url.URL, error)) ClientOption {
	return engine.WithProxy(proxy)
}

// WithRetry sets the retry policy of every call the client makes, unless a
// call passes its own with [Retry]; [DefaultRetry] unless set. A policy with
// a setting out of range fails NewClient with a [*ConfigError] that carries
// the Python SDK's message ([RetryPolicy]).
func WithRetry(policy RetryPolicy) ClientOption {
	return engine.WithRetry(policy)
}

// WithRootCAs sets the certificate authorities the client trusts for the
// API host and an https proxy. A non-nil pool replaces the RootCAs of
// [WithTLSConfig]'s configuration; nil keeps that configuration's RootCAs,
// which are the system's when it sets none or when there is no
// [WithTLSConfig]. It configures the SDK's own transport, so it cannot be
// combined with [WithHTTPTransport] or [WithRoundTripper].
func WithRootCAs(pool *x509.CertPool) ClientOption {
	return engine.WithRootCAs(pool)
}

// WithRoundTripper makes the client send every request through rt as it is:
// no connection policy, no ALPN check, no cold-start gate. The client's
// per-attempt deadline and response size limit still apply. Closing the
// client closes rt's idle connections when rt has a CloseIdleConnections
// method, as an [*http.Transport] has, and then closes rt when it is an
// [io.Closer], each once. rt owns its connection timeouts, so it cannot be
// combined with [WithHTTPTransport], [WithHTTPVersion], [WithRootCAs],
// [WithTLSConfig], [WithProxy] or [WithConnectTimeout]. A nil rt is refused.
//
// rt must not modify a request, as the [net/http.RoundTripper] contract
// already requires: the first attempt of every call hands it the client's
// own header map, shared by every call and never copied, so a RoundTripper
// that writes to req.Header changes the headers of later calls and races
// with concurrent ones. Each request carries its own copy of the endpoint
// URL.
func WithRoundTripper(rt http.RoundTripper) ClientOption {
	return engine.WithRoundTripper(rt)
}

// WithRuntimeHeader sets whether requests carry X-TypeSafe-Runtime, which
// names the Go release, operating system and architecture the program was
// built for, such as go/1.27.1 (linux; amd64). The default is true; false
// leaves the header out of every request. X-TypeSafe-SDK is sent either way.
func WithRuntimeHeader(send bool) ClientOption {
	return engine.WithRuntimeHeader(send)
}

// WithTLSConfig sets the TLS configuration the client starts from; it is
// cloned when the option is applied. The SDK raises MinVersion to TLS 1.2 and
// runs its own ALPN check after the configuration's VerifyConnection; a
// non-nil pool given to [WithRootCAs] replaces RootCAs. It configures the
// SDK's own transport, so it cannot be combined with [WithHTTPTransport] or
// [WithRoundTripper].
func WithTLSConfig(cfg *tls.Config) ClientOption {
	return engine.WithTLSConfig(cfg)
}

// WithTimeout sets the deadline of each attempt of a request, from sending
// the request to reading the whole response; [DefaultTimeout] unless set. It
// must be positive; [WithNoTimeout] removes the deadline, and the two cannot
// be used together.
func WithTimeout(d time.Duration) ClientOption {
	return engine.WithTimeout(d)
}

// WithUserAgentProduct names the application in the User-Agent header, in
// front of the SDK's own product, the more significant product first (RFC
// 9110, section 10.1.5): "my-app/1.2.0" sends
// User-Agent: my-app/1.2.0 typesafe-sdk-go/<Version>. Unset, User-Agent is
// typesafe-sdk-go/<Version> alone, the form typesafe-sdk-python sends its own
// name in (py:_core/transport.py:123). X-TypeSafe-SDK always names the SDK
// alone.
//
// The product must be name/version, both parts tokens (RFC 9110, section
// 5.6.2: letters, digits and !#$%&'*+-.^_`|~), with exactly one "/" and at
// most 64 bytes in all. A product that breaks those rules is refused by name
// of the rule; the error does not repeat it.
func WithUserAgentProduct(product string) ClientOption {
	return engine.WithUserAgentProduct(product)
}
