// Command _gen writes the root package's facade over internal/engine for the
// W6.5 design spike D2: an alias per exported type, a constant or variable
// per exported value, a wrapper per exported function, each with the
// engine's doc comment.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/doc"
	"go/importer"
	"go/parser"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const enginePath = "github.com/zchee/typesafe-sdk-go/internal/engine"

func main() {
	fset := token.NewFileSet()
	pkg, err := importer.ForCompiler(fset, "source", nil).Import(enginePath)
	if err != nil {
		panic(err)
	}
	// Doc comments from the engine's non-test sources.
	docs := map[string]string{}
	files, _ := filepath.Glob("internal/engine/*.go")
	pf := token.NewFileSet()
	for _, f := range files {
		if strings.HasSuffix(f, "_test.go") {
			continue
		}
		af, err := parser.ParseFile(pf, f, nil, parser.ParseComments)
		if err != nil {
			panic(err)
		}
		for _, d := range af.Decls {
			switch d := d.(type) {
			case *ast.FuncDecl:
				if d.Recv == nil && d.Doc != nil {
					docs[d.Name.Name] = d.Doc.Text()
				}
			case *ast.GenDecl:
				for _, s := range d.Specs {
					var names []*ast.Ident
					var sdoc *ast.CommentGroup
					switch s := s.(type) {
					case *ast.TypeSpec:
						names, sdoc = []*ast.Ident{s.Name}, s.Doc
					case *ast.ValueSpec:
						names, sdoc = s.Names, s.Doc
					}
					if sdoc == nil && len(d.Specs) == 1 {
						sdoc = d.Doc
					}
					for _, n := range names {
						if sdoc != nil {
							docs[n.Name] = sdoc.Text()
						}
					}
				}
			}
		}
	}
	qual := func(p *types.Package) string {
		if p.Path() == enginePath {
			return ""
		}
		return p.Name()
	}
	comment := func(b *bytes.Buffer, name string) {
		text := docs[name]
		if text == "" {
			return
		}
		var out bytes.Buffer
		p := new(doc.Package).Printer()
		_ = p
		for _, line := range strings.Split(strings.TrimRight(text, "\n"), "\n") {
			if line == "" {
				out.WriteString("//\n")
			} else {
				out.WriteString("// " + line + "\n")
			}
		}
		b.Write(out.Bytes())
	}
	var b bytes.Buffer
	b.WriteString("package typesafe\n\n// Code generated by the W6.5 design spike's _gen (D2); the public API is\n// declared in internal/engine and re-exported here.\n\nimport \"github.com/zchee/typesafe-sdk-go/internal/engine\"\n\n")
	names := pkg.Scope().Names()
	sort.Strings(names)
	for _, name := range names {
		obj := pkg.Scope().Lookup(name)
		if !obj.Exported() {
			continue
		}
		switch name { // exported for internal/alloctest only
		case "Request", "HeaderRedactor", "Credentials", "BodyMember", "SystemOneAlloc",
			"InitialUndeclared", "MaxInlineAnswers", "ModelsPath":
			continue
		}
		switch obj := obj.(type) {
		case *types.TypeName:
			comment(&b, name)
			tp := ""
			args := ""
			if n, ok := obj.Type().(*types.Named); ok && n.TypeParams().Len() > 0 {
				var ps, as []string
				for i := range n.TypeParams().Len() {
					t := n.TypeParams().At(i)
					ps = append(ps, t.Obj().Name()+" "+types.TypeString(t.Constraint(), qual))
					as = append(as, t.Obj().Name())
				}
				tp, args = "["+strings.Join(ps, ", ")+"]", "["+strings.Join(as, ", ")+"]"
			}
			fmt.Fprintf(&b, "type %s%s = engine.%s%s\n\n", name, tp, name, args)
		case *types.Const:
			comment(&b, name)
			if basic, ok := obj.Type().(*types.Basic); ok && basic.Info()&types.IsUntyped != 0 {
				fmt.Fprintf(&b, "const %s = engine.%s\n\n", name, name)
			} else {
				fmt.Fprintf(&b, "const %s %s = engine.%s\n\n", name, types.TypeString(obj.Type(), qual), name)
			}
		case *types.Var:
			comment(&b, name)
			fmt.Fprintf(&b, "var %s = engine.%s\n\n", name, name)
		case *types.Func:
			// Accessors for internal/alloctest stay in the engine.
			switch name {
			case "ConfigOf", "SystemOneEndpointOf", "ResponseMetaOf", "ResponseResultOf", "WireOf",
				"EncodeBody", "AppendState", "DecodeSystemOne", "DecodeSystemOneInto", "ReadBody",
				"NewSystemOneAlloc", "NewHeaderRedactor", "IsSecretHeader", "RequestCredentials", "FalsyJSON":
				continue
			}
			comment(&b, name)
			sig := obj.Signature()
			var tps, targs []string
			for i := range sig.TypeParams().Len() {
				t := sig.TypeParams().At(i)
				tps = append(tps, t.Obj().Name()+" "+types.TypeString(t.Constraint(), qual))
				targs = append(targs, t.Obj().Name())
			}
			var params, args []string
			for i := range sig.Params().Len() {
				p := sig.Params().At(i)
				pn := p.Name()
				if pn == "" || pn == "_" {
					pn = fmt.Sprintf("p%d", i)
				}
				t := types.TypeString(p.Type(), qual)
				if sig.Variadic() && i == sig.Params().Len()-1 {
					t = "..." + types.TypeString(p.Type().(*types.Slice).Elem(), qual)
					args = append(args, pn+"...")
				} else {
					args = append(args, pn)
				}
				params = append(params, pn+" "+t)
			}
			var res []string
			for i := range sig.Results().Len() {
				res = append(res, types.TypeString(sig.Results().At(i).Type(), qual))
			}
			r := ""
			switch len(res) {
			case 0:
			case 1:
				r = " " + res[0]
			default:
				r = " (" + strings.Join(res, ", ") + ")"
			}
			tp, ta := "", ""
			if len(tps) > 0 {
				tp, ta = "["+strings.Join(tps, ", ")+"]", "["+strings.Join(targs, ", ")+"]"
			}
			ret := "return "
			if len(res) == 0 {
				ret = ""
			}
			fmt.Fprintf(&b, "func %s%s(%s)%s {\n\t%sengine.%s%s(%s)\n}\n\n", name, tp, strings.Join(params, ", "), r, ret, name, ta, strings.Join(args, ", "))
		}
	}
	lic, _ := os.ReadFile("doc.go")
	header := string(lic[:bytes.Index(lic, []byte("package "))])
	header = header[:strings.LastIndex(strings.TrimRight(header, "\n"), "\n\n")+1]
	if err := os.WriteFile("api.go", append([]byte(strings.SplitAfter(string(lic), "limitations under the License.\n")[0]+"\n"), b.Bytes()...), 0o644); err != nil {
		panic(err)
	}
}
